### ISSUE TITLE
Marcar informações geradas automáticas como warning

### ISSUE THREAD

**Issue by izacsc** [AlencarGabriel/ProtheusDoc-VsCode#13]
Muitas vezes quando estamos fazendo a documentação apertamos o atalho de geração de documentação e esquecemos de preencher o conteúdo. 

Marcar como warning propriedades de descrição que estejam com o valor gerado automático.

**Comment by AlencarGabriel** [comment]
Olá @izacsc ,

muito interessante sua solicitação, hoje o TDS tem esse comportamento como um "marcador" de linha quando o conteúdo do ProtheusDoc está inválido.

Vou avaliar sua solicitação e volto a informar. Obrigado novamente por sua colaboração!

**Comment by izacsc** [comment]
Por nada!

Eu me lembro dessa funcionalidade do TDS mas as vezes acabava atrapalhando. No setor onde eu trabalhava, nós colocávamos uma propriedade customizada ( @project ) e todos os cabeçalhos ficavam com erro. A ideia aqui ( pelo menos pra mim ) é mostrar o que foi gerado automático e ainda não foi preenchido, como a descrição da função, de parâmetros e de retornos.

**Comment by AlencarGabriel** [comment]
Sim, entendi sua questão. 

Imaginando como seria vejo que validaria o conteúdo mesmo, mas somente das propriedades que eu trato, pois na Documentação do ProtheusDoc no TDN tem inúmeras outras propriedades que não tratei por considerar "desnecessárias".

**Comment by AlencarGabriel** [comment]
Olá @izacsc ,

acha interessante essa análise das inconsistências do ProtheusDoc ser somente para o fonte aberto, ou avaliar a workspace inteira?

**Comment by izacsc** [comment]
Opa, tá corrido aqui rs.

Acredito que no só fonte aberto. E talvez um comando pra analisar a workspace inteira. Analisar tudo deve ficar muito custoso.

Abraço

**Comment by AlencarGabriel** [comment]
@izacsc , finalizei a implementação dos diagnósticos do ProtheusDoc, poderia instalar essa versão em seu ambiente e verificar se atende as necessidades?

[protheusdoc-vscode-0.6.0.zip](https://github.com/AlencarGabriel/ProtheusDoc-VsCode/files/4737477/protheusdoc-vscode-0.6.0.zip)

Obs.: Não implementei ainda a validação da Workspace, vou deixar para fazer posteriormente.

**Comment by izacsc** [comment]
Boa tarde! A ideia é essa mesmo. Só não foi implementado pra descrição da função:

![image](https://user-images.githubusercontent.com/423449/83905220-afa3aa00-a737-11ea-81a6-7167ecaa4b51.png)

**Comment by AlencarGabriel** [comment]
Opa, 

então, eu até implementei pra descrição. Porém pelo visto só detectei se não está informada. Já ajusto aqui. 

Coloquei validação de vários atributos (type, param, return, since, author e history) e também caso estejam faltantes como @type e @author.

**Comment by AlencarGabriel** [comment]
Segue a versão com a descrição corrigida:

[protheusdoc-vscode-0.6.0.zip](https://github.com/AlencarGabriel/ProtheusDoc-VsCode/files/4737633/protheusdoc-vscode-0.6.0.zip)

**Comment by izacsc** [comment]
Ah, eu ia comentar justamente isso... Eu só validaria o que foi colocado.

![image](https://user-images.githubusercontent.com/423449/83906923-cef00680-a73a-11ea-89d3-6fe27a2cb67d.png)

Aqui foi por opção que eu não quis documentar o resto... 

Mas o negócio tá começando a ficar complexo rs Mas poderia estar atrás de uma opção para escolher quais atributos são obrigatórios.

Mas tá ficando muito bom

**Comment by izacsc** [comment]
Mais um pequeno ponto rs
Você tá validando o formato do que tá escrito. Apesar de ser interessante, tem gente que tem outros padrões. 

![image](https://user-images.githubusercontent.com/423449/83907394-b6ccb700-a73b-11ea-95c8-0a2f9979d163.png)

Então pra todos os outros que não seguem esse padrão de descrição de conteúdo, ele apresentaria erro também.

Abraço

**Comment by AlencarGabriel** [comment]
Então, toda a extensão é baseada na convenção documentada pela própria TOTVS (https://tdn.totvs.com/display/tec/ProtheusDOC)

Esse tipo de situação causaria colateriais em diversos pontos da extensão como: Documentação HTML, Hover do Identificador, etc... Pois todos estes funcionam conforme a estrutura padrão.

Ai como é uma coisa fora do padrão fica difícil tratar.

Posso fazer uma coisa para contornar isso, criar uma configuração para definir quais atributos não serão validados. O que acha?

**Comment by izacsc** [comment]
Sim, eu entendo. Mas raramente a convenção é seguida ao pé da letra rs

Acho que criar a configuração para validar é uma boa. Assim que começar a usar a extensão pode escolher não ver um monte de erros numa base que não esteja padronizada.

Pergunta, isso desativaria a verificação do preenchimento automático?

**Comment by AlencarGabriel** [comment]
Pois é, infelizmente em muitos casos não são seguidas mesmo e podem causar problemas que só serão identificados no futuro.

Quanto a sua pergunta, eu faço a validação do arquivo inteiro para verificar se alem dos valores padrões (ou vazios) a sintaxe do ProtheusDoc de alguns atributos essenciais está correta.

Nessa configuração que sugeri, no seu caso você poderia configurar para não validar o atributo @param. Isso não afetaria as outras validações, somente as deste atributo.

**Comment by AlencarGabriel** [comment]
Olá @izacsc ,

finalizei os ajustes em todos os atributos e adicionei as configurações conforme conversamos.

Se puder validar essa versão, eu agradeço.

[protheusdoc-vscode-0.6.0.zip](https://github.com/AlencarGabriel/ProtheusDoc-VsCode/files/4788943/protheusdoc-vscode-0.6.0.zip)

Ah, fiz uma Wiki somente sobre este recurso https://github.com/AlencarGabriel/ProtheusDoc-VsCode/wiki/Diagnóstico-das-documentações, lá eu explico as validações que são feitas e as configurações relacionadas.

Qualquer coisa só me falar.

 Aguardo teu feedback.

**Comment by AlencarGabriel** [comment]
Implementado na versão `0.7.0`.
