### ISSUE TITLE
Documentação de Static Functions não devem ser apresentadas fora do próprio fonte.

### ISSUE THREAD

**Issue by izacsc** [AlencarGabriel/ProtheusDoc-VsCode#15]
Ao fazer o hover de uma função estática, deveria ser apresentada somente a documentação da função daquele fonte.

Isso fica claro com a função ModelDef, por exemplo.

Abraço

**Comment by AlencarGabriel** [comment]
Boa tarde @izacsc ,

interessante sua solicitação. Eu tive esse problema, não com `MenuDef()` (não documento essas) mas com Métodos `New()`, por isso fiz o Hover apresentar todas as ocorrências encontradas. 

Mas faz sentido ao invés de duplicar trazer do fonte atual caso a ocorrência se repita em outros fontes.

Por conta do Hover não estar implementado usando a inteligencia do Language Server, eu não sei se uma função é `User` ou `Static`, apenas se é Função, Método ou Classe. 

Mas vou analisar com calma sua solicitação e a gente volta a conversar.
