### ISSUE TITLE
Não considera a tipagem definida

### ISSUE THREAD

**Issue by izacsc** [AlencarGabriel/ProtheusDoc-VsCode#2]
Bom dia!

Ao documentar uma função que tenha os parâmetros e/ou retorno tipado, deveria assumir os definidos e não tentar adivinhar.

Resultado:
![image](https://user-images.githubusercontent.com/423449/72985273-62e0b780-3dc4-11ea-93e9-9ad86923fedd.png)

Esperado:

![image](https://user-images.githubusercontent.com/423449/72985330-8d327500-3dc4-11ea-8198-9d1e6acd8318.png)

**Comment by AlencarGabriel** [comment]
Olá @izacsc , bom dia!

Obrigado pela sua issue. Realmente essas sintaxe TLPP não foi tratada, fiz um teste no TDS e pelo visto lá também não está.

Bem, vou implementar então essa sintaxe Tl++ e te informo.

**Comment by izacsc** [comment]
Legal @AlencarGabriel, mas só pra conhecimento, essa é uma sintaxe totalmente válida pra AdvPL também e não só pra TL++:

https://tdn.totvs.com/display/tec/Tipagem+de+Dados

E parabéns pela extensão!
Abraço

**Comment by AlencarGabriel** [comment]
Obrigado @izacsc , espero contribuir ainda mais com a comunidade.

Acabei de ver aqui, realmente desconhecia isso para AdvPL. Para mim só ia funcionar no Tlpp. 

Fiz alguns testes aqui, e realmente, agora inclusive vou adotar. Obrigado pela informação!

**Comment by AlencarGabriel** [comment]
![Issue #2](https://user-images.githubusercontent.com/10109480/73084864-867f2d00-3eac-11ea-9d5c-80ed8654c32c.gif)


Boa tarde @izacsc , 

segue comportamento final após os ajustes conforme solicitado. 

Novamente obrigado por reportar o problema.
