### ISSUE TITLE
Parte do texto nas descrições não é documentado

### ISSUE THREAD

**Issue by denisgalvani** [AlencarGabriel/ProtheusDoc-VsCode#35]
Ao utilizar vírgula (,) na descrição das propriedades @param e @return o conteúdo após a vírgula não é incluído na documentação.

## Exemplo:
> @param cParam1, character, Descrição do parâmetro, ref. ao campo "ABC_XYZ"
> @return NULL, Nenhum, vazio

- [ ] "Descrição" com vírgula não são totalmente incluídas na documentação HTML;
- [ ] Coluna "Descrição", na tabela "Parâmetros" omite conteúdo - _, ref. ao campo "ABC_XYZ"_;
- [ ] Coluna "Descrição", na tabela "Retorno" omite conteúdo - _, vazio_

## Exemplo - Resultado na Documentação HTML:

> **Parâmetros**
> |Nome|Tipo|Descrição|
> |---|---|---|
> |cParam1|character|Descrição do parâmetro|
>
> **Retorno**
> |Tipo|Descrição|
> |---|---|
> |NULL|Nenhum|

## Conteúdo correto esperado 
Na Documentação HTML, para este Exemplo:

> **Parâmetros**
> |Nome|Tipo|Descrição|
> |---|---|---|
> |cParam1|character|Descrição do parâmetro **, ref. ao campo "ABC_XYZ"**|
>
> **Retorno**
> |Tipo|Descrição|
> |---|---|
> |NULL|Nenhum **, vazio**|

**Comment by AlencarGabriel** [comment]
Olá @denisgalvani , obrigado por informar o problema. 

Vamos estar verificando e retornaremos o contato.

**Comment by AlencarGabriel** [comment]
Adicionado na versão **0.6.1**. Obrigado por sua colaboração @denisgalvani .
