### ISSUE TITLE
Primeiramente muito obrigado! "Segundamente..."

### ISSUE THREAD

**Issue by RSGomes** [AlencarGabriel/ProtheusDoc-VsCode#37]
Primeiramente muito obrigado Gabriel essa extensão é show mesmo! O quão difícil seria ter mais uma sessão com os parâmetros de sistema (SX6) encapsulados dentro de cada função avaliada? :)

**Comment by AlencarGabriel** [comment]
Olá @RSGomes obrigado pelo feedback e fico feliz que tenha te ajudado.

Quanto sua solicitação, se entendi bem você gostaria de ter mais um atributo ProtheusDoc (@) suportado?

Eu adotei nesse projeto a premissa de implementar apenas os atributos ProtheusDoc padrões, conforme essa documentação: https://tdn.totvs.com/display/tec/ProtheusDOC

Seria isso mesmo que você gostaria para ver se entendo bem?

**Comment by RSGomes** [comment]
> Quanto sua solicitação, se entendi bem você gostaria de ter mais um atributo ProtheusDoc (@) suportado?
Sim essa era a ideia. Mas não consigo imaginar o trabalho que seria avaliar para dentro de uma função, buscando toda e qualquer função de carga de Parâmetro do SX6 (SuperGetMV, GetNewPar e assim vai...) para trazê-los automaticamente e criar uma seção nova no cabeçalho do código.

Eu vejo que é um prática muito comum definir certas porções das regras de negócio nos parâmetros, visto a possibilidade de se ajustar seu conteúdo sem mexer o código fonte. E com certeza o documento gerado através da sua ferramenta, se bem escrito, pode ser uma leitura bem mais agradável e clara do que muitos códigos fontes por aí o que facilitaria e muito compreender a relação entre funções e o que deveria ser validado antes de uma nova implementação.

**Comment by AlencarGabriel** [comment]
Entendo perfeitamente sua colocação @RSGomes .

Porém não tinha imaginado algo tão dinâmico assim, pois foge um pouco das premissas desta extensão. 

Quanto as RN em parâmetros, concordo plenamente, mas acho que o impacto dessa implementação não "pagaria" o seu uso, visto ser possível o próprio analista no desenvolvimento implementar outros atributos padrões como `@obs` ou `@see` e ali descrever os parâmetros utilizados da forma que achar melhor. E ambos atributos são considerados na documentação HTML.

**Comment by RSGomes** [comment]
Tem razão. Apesar de não serem seções específicas para o caso, tanto a @obs quanto a @see podem dar conta do situação. Abs!

**Comment by tgmti** [comment]
Olá, sei que já fecharam a Issue. Mas vou dar um pitaco.

O @AlencarGabriel indicou que a premissa é implementar somente os atributos ProtheusDoc padrões, baseadas no TDN. E concordo com isso.

Porém também vi mais de uma Issue aqui com solicitações parecidas, de estender as funcionalidades, ou implementar outros atributos.

Minha sugestão é discutirmos uma forma de implementar plugins customizáveis na extensão.
Não sei como seria a melhor forma, se através de arquivos de configuração ou extensões separadas.

Mas seria bastante interessante algo nesse sentido, pois cada um poderia criar e compartilhar novas features, compatíveis ou não com o padrão da TOTVS, sem descaracterizar a proposta padrão da extensão.

Como disse, é só um pitaco. Mas se alguém mais estiver de acordo, podemos abrir uma nova issue para discutir isso. E se a coisa evoluir, espero conseguir contribuir nas atividades de desenvolvimento e testes.

**Comment by AlencarGabriel** [comment]
Olá @tgmti , sua sugestão é um desejo meu há muito tempo de implementar pontos de contribuição, semelhante a arquitetura do VsCode. 

Fiz um trabalho bacana com o Rodrigo há uns anos na extensão http://github.com/totvs/advpl-vscode para que minha outra extensão de gerenciamento de projetos integrasse com a dele https://github.com/AlencarGabriel/advpl-switch-project de suporte a AdvPL (unica existente na época).

Não sei qual issue você estava se referindo, mas praticamente todas as issues foram abertas por mim mesmo. Por exemplo issues para adicionar suporte a atributos, era para adicionar atributos documentados que eu ainda não tinha implementado (e ainda nem implementei todos). O restante eram features do próprio VsCode que seriam úteis como diagnóstico (vai sair na próxima versão) e hover de documentações. 

Mas acho válido discutirmos sobre essa possibilidade aqui na extensão. Vai abrir muitas portas!

**Comment by tgmti** [comment]
Opa, legal. Issue criada #38 . Vou me coçar aqui e ver no que consigo ajudar :grin:

Sobre essa parte:

> Não sei qual issue você estava se referindo...

eu acompanhado as Issues deste e de outros repos por e-mail. Então provavelmente me confundi em alguma discussão :stuck_out_tongue_winking_eye:
