### ISSUE TITLE
Snippets precedidas por espaço não reconhecidas

### ISSUE THREAD

**Issue by denisgalvani** [AlencarGabriel/ProtheusDoc-VsCode#40]
Ao gerar a documentação ProtheusDoc acima da função as snippets _@type_, _@author_, _@since_, _@version_ quando possuem espaçamento para alinhamento/formatação ao gerar Documentação HTML seus conteúdos não são considerados e devidamente formatados.

Para correta geração e formatação da Documentação HTML as chaves devem permanecer no início da linha, sem espaço a esquerda.

 /*/{Protheus.doc} MyFunc
{{TAB}}Função estática geral.
{{TAB}}@type 		function
{{TAB}}@author 		denis.galvani
{{TAB}}@since 		05/04/2019
{{TAB}}@version 	2.0
{{TAB}}@param 		aMvPar		, array		, Parâmetros de pesquisa via *Pergunte*
{{TAB}}@param 		lJob			, logical		, Execução via JOB ou rotina de reprocessamento (por usuário)
{{TAB}}@return 		array		, Valores de parâmetros de *Pergunta* de acordo com tipo de execução *(JOB ou usuário)*
{{TAB}}@see 		- Parâmetros *(SC6)*: MV_STALM, MV_TPLIM, MV_DIATR;
{{TAB}}{{TAB}}		- Pergunte *(SX1)* - *"LIBCRDT"*
{{TAB}}@history 	denis.galvani, 22/08/2020, denis.galvani, Inclusão/padronização de documentação de cabeçalho
{{TAB}}/*/
Static Function MyFunc(aMvPar,lJob)

**Comment by AlencarGabriel** [comment]
Olá @denisgalvani ,

fiz alguns testes para simular o problema repassado conforme cenário apresentado, porém não consegui reproduzir.

- Veja que aqui eu adicionei a documentação utilizando TAB antes dos atributos:
 ![image](https://user-images.githubusercontent.com/10109480/92595032-1c1fcf00-f27a-11ea-8484-58160159d15f.png)

- Aqui é o resultado da documentação HTML (testei tanto exportando pela workspace e somente do arquivo):
![image](https://user-images.githubusercontent.com/10109480/92595068-28a42780-f27a-11ea-88d6-161ac79a35e5.png)

Poderia me dar mais detalhes do problema para que eu possa te ajudar melhor?
