### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by sandro-costa** [AlencarGabriel/ProtheusDoc-VsCode#45]
- Issue Type: `Performance`
- Extension Name: `protheusdoc-vscode`
- Extension Version: `0.6.1`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.52.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\SANDRO~1.COS\AppData\Local\Temp\AlencarGabriel.protheusdoc-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

[AlencarGabriel.protheusdoc-vscode-unresponsive.cpuprofile.txt](https://github.com/AlencarGabriel/ProtheusDoc-VsCode/files/5681769/AlencarGabriel.protheusdoc-vscode-unresponsive.cpuprofile.txt)

**Comment by AlencarGabriel** [comment]
Olá @sandro-costa ,

obrigado por informar o problema. Com sua ajuda pude identificar um trecho inutilizado da extensão que estava causando alto custo de processamento quando haviam muitas documentações ProtheusDoc na workspace.

CPU Before:
![image](https://user-images.githubusercontent.com/10109480/102119713-51f7c500-3e20-11eb-9834-c563128fc554.png)

CPU After:
![image](https://user-images.githubusercontent.com/10109480/102119689-4a382080-3e20-11eb-8e1e-5efe97d5a854.png)

**Comment by AlencarGabriel** [comment]
Corrigido na 0.7.3.

**Comment by sandro-costa** [comment]
Fechou meu nobre... TMJ

At,

Sandro Costa

De: Gabriel Alencar <notifications@github.com>
Enviada em: quinta-feira, 17 de dezembro de 2020 17:03
Para: AlencarGabriel/ProtheusDoc-VsCode <ProtheusDoc-VsCode@noreply.github.com>
Cc: sandro-costa <sandrosc@outlook.com>; Mention <mention@noreply.github.com>
Assunto: Re: [AlencarGabriel/ProtheusDoc-VsCode] Extension causes high cpu load (#45)


Closed #45<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAlencarGabriel%2FProtheusDoc-VsCode%2Fissues%2F45&data=04%7C01%7C%7C5a409de6b8ed4e3aee4508d8a2c6cc71%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637438322002197237%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NaQal%2Bi7zjBopFd6IcdmkVubJtBo26%2FYbuZMfpRColU%3D&reserved=0>.

-
