### ISSUE TITLE
Parâmetro Opcional no ProtheusDoc

### ISSUE THREAD

**Issue by carloseniemeyer** [AlencarGabriel/ProtheusDoc-VsCode#50]
Seria possível que essa engine do ProtheusDoc considerasse os parâmetros entre colchetes como parâmetros opcionais?

(https://tdn.totvs.com/display/tec/ProtheusDOC)

**Exemplo:**
@param nBase, numérico, Medida do lado ou da base
@param [nAltura], numérico, Medida da altura
@param [nBaseMenor], numérico, Medida da base menor (trapézios)

Os 2 últimos parâmetros são opcionais.

Hoje o diagnóstico está considerando como um erro no ProtheusDoc.
Seria muito interessante que isso fosse considerado tanto no diagnóstico, como na geração HTML (Informando o termo "**Opcional**" ao lado do parâmetro). 

Isso evita termos que descrever na descrição do parâmetro se ele é opcional ou obrigatório.

**Comment by AlencarGabriel** [comment]
Olá @carloseniemeyer ,

desde já obrigado por sua issue. Sua solicitação é bastante interessante, visto que na versão do antigo TDS Eclipse isso funcionava realmente:
![image](https://user-images.githubusercontent.com/10109480/104942825-ac41f380-5993-11eb-97dc-fdb12b5ce584.png)

Na época que desenhei essa extensão havia deixado de lado essa questão. Mas vou analisar sua solicitação e realizar os ajustes necessários. 

Obrigado por informar, qualquer coisa relacionado a isso volto a falar por aqui.

**Comment by carloseniemeyer** [comment]
Excelente notícia!

**Comment by AlencarGabriel** [comment]
Olá @carloseniemeyer ,

venho informar que a implementação solicitada já foi desenvolvida, tanto aqui no lado da extensão, quando na dependência da documentação HTML (robsonrosilva/protheusDoc#4).

Resultado na extensão: 
![image](https://user-images.githubusercontent.com/10109480/111355108-cdf2ea80-8665-11eb-8052-2fb20d8b7043.png)

Agora não irá mais causar erros no diagnóstico quando o parâmetro for opcional, e no hover será informado.

Resultado no HTML:
![image](https://user-images.githubusercontent.com/10109480/111354645-4b6a2b00-8665-11eb-9538-3cf914420674.png)

Aguardando apenas a liberação do novo pacote da dependência, para lançamento da próxima versão aqui da extensão ProtheusDoc.

**Comment by AlencarGabriel** [comment]
Documentação da feature: https://github.com/AlencarGabriel/ProtheusDoc-VsCode/wiki/Hover-de-documentações#parâmetros-opcionais
