### ISSUE TITLE
Aparece como advertencia na compilação

### ISSUE THREAD

**Issue by jadilsonnery** [AlencarGabriel/ProtheusDoc-VsCode#51]
Segue imagem das advertências. O que fazer ??
![TELA](https://user-images.githubusercontent.com/64595947/105075822-08c31280-5a69-11eb-9499-c9179ae0d165.jpg)

**Comment by AlencarGabriel** [comment]
Olá @jadilsonnery ,

isto refere-se aos diagnósticos do ProtheusDoc. Foi implementado em algumas versões atrás para permitir que os usuários possam desfrutar de todos os recursos da extensão, usando o ProtheusDoc segundo sua convenção.

Portanto sempre que um fonte for aberto, o mesmo será diagnosticado e as ocorrências reportadas na aba de problemas (não é uma validação de compilação).

Cada validação possui a informação de qual é o problema e o que deve ser feito para solucionar.

É possível desativar estas validações no geral, ou alguma opcional em específico. Dá uma conferida na [Wiki de Diagnósticos](https://github.com/AlencarGabriel/ProtheusDoc-VsCode/wiki/Diagn%C3%B3stico-das-documenta%C3%A7%C3%B5es), lá tem todas as informações sobre essa feature.

Fico a disposição.
