### ISSUE TITLE
Snippets não são reconhecidas em bloco ProtheusDoc precedido por espaço

### ISSUE THREAD

**Issue by dgo-angelo** [AlencarGabriel/ProtheusDoc-VsCode#54]
Bom dia, tudo bem?

Dependendo da indentação do bloco do ProtheusDoc, as snippets não são reconhecidas corretamente, por exemplo:

Fonte:
![image](https://user-images.githubusercontent.com/44792717/105361873-eea84200-5bd8-11eb-8c35-38b2617fa264.png)

HTML Gerado:

![image](https://user-images.githubusercontent.com/44792717/105361973-126b8800-5bd9-11eb-8f30-01f10b7ede1f.png)

Atenciosamente,

**Comment by AlencarGabriel** [comment]
Olá @dgo-angelo ,

obrigado por informar o problema. Há um tempo atrás abriram uma issue parecida (#40) porém não me retornaram com as evidencias. Agora consegui simular aqui, mas tive que dar 2 tabs para acontecer. 

Vou direcionar sua issue para o repositório responsável pela geração da documentação HTML.

**Comment by robsonrosilva** [comment]
@AlencarGabriel problema corrigido.
Favor testar na nova versão 1.1.3.

**Comment by AlencarGabriel** [comment]
Obrigado @robsonrosilva ,

testei aqui e funcionou certinho. Já já subo a versão nova.
