### ISSUE TITLE
Informar versão padrão inicial

### ISSUE THREAD

**Issue by danielscheeren** [AlencarGabriel/ProtheusDoc-VsCode#59]
Adicionar na configuração uma opção para trazer uma versão inicial padrão ao inserir uma nova documentação.
Exemplo: @version 1.0

**Comment by AlencarGabriel** [comment]
Olá @danielscheeren ,

essa configuração já existe: `protheusDoc.versao_default`.

Inclusive, como **@version** é um atributo opcional, este pode ainda ser omitido do gerador de documentações, por meio da configuração `protheusDoc.marcadores_ocultos`.

Mais informações vide wiki: [Configurações](https://github.com/AlencarGabriel/ProtheusDoc-VsCode/wiki/Configura%C3%A7%C3%B5es).

Espero ter esclarecido.
