### ISSUE TITLE
Adaptação da Tag @see com Múltiplos

### ISSUE THREAD

**Issue by carloseniemeyer** [AlencarGabriel/ProtheusDoc-VsCode#61]
Gabriel,
Boa Tarde!
Ao gerar as documentações em HTML foi percebido que o Gerador do ProtheusDoc não está considerando várias tags @see.
Ele está considerando apenas a última tag colocada.

Exemplo:
```
@see Vide Função u_FATH9Manutencao()
@see Vide Função u_FATH9ItensCons()
```

**Na documentação do ProtheusDoc ele cita que aceita múltiplos "@see".**
https://tdn.totvs.com/display/tec/ProtheusDOC

**Comment by AlencarGabriel** [comment]
Implementado na versão **0.10.0**.
