### ISSUE TITLE
Tipo de Conteúdo Undefined nas tags @param e @return

### ISSUE THREAD

**Issue by carloseniemeyer** [AlencarGabriel/ProtheusDoc-VsCode#63]
Gabriel,

Boa Tarde!

Em algumas situações precisamos documentar um determinado parâmetro e retorno de uma função ADVPL que não tem um tipo específico, mas que também não é um variadic.

Exemplo:
```

@param cField, character, Nome do Campo
@param uContent, undefined, Conteúdo do Campo Pode ser Data, Caracter ou Numérico
@param nRecord, numeric, Número do Registro

Static Function setValue(cField,uContent,nRecord)
...
Return lRet

@return undefined, Conteúdo do Campo Pode ser Data, Caracter ou Numérico

Static Function getValue(cField,nRecord)
...
Return uContent
```

**Comment by AlencarGabriel** [comment]
Implementado suporte ao tipo **variant** 1abad41.

**Comment by AlencarGabriel** [comment]
Disponível a partir da versão **0.9.0**.

Caso não seja detectado/informado um tipo, será assumido o tipo `variant` pelo ProtheusDoc, mesmo que o fonte seja AdvPL e não TL++.
