### ISSUE TITLE
Atualizar os tipos permitidos de acordo com a tabela oficial

### ISSUE THREAD

**Issue by rodrigopg** [AlencarGabriel/ProtheusDoc-VsCode#64]
Atualmente na linguagem TLPP existem vários tipos nativos além dos básicos do ADVPL.

https://tdn.totvs.com/display/tec/Tipos+Nativos

Ao utilizar os novos tipos do TLPP na documentação está sendo apresentado warning de tipo inválido.

<img width="323" alt="Screen Shot 2021-05-21 at 16 25 42" src="https://user-images.githubusercontent.com/5282959/119188569-350b9180-ba51-11eb-9660-e65a076cfa66.png">

**Comment by AlencarGabriel** [comment]
Olá @rodrigopg, 

estamos terminando de fechar alguns assuntos referente as novas mudanças do TL++ aqui na TOTVS, e vamos atualizar as extensões o quanto antes com as novidades. Já está aqui no radar.

De qualquer forma, se esses warnings estiverem incomodando, pode estar utilizando a configuração `protheusDoc.marcadores_nao_validar` para suprimi-los por hora, enquanto a correção não sai.

Agradeço o feedback.

**Comment by AlencarGabriel** [comment]
Adicionado suporte aos novos tipos do TLPP:

Tipo | Sigla | Type no Protheus Doc |
-----|-------|--------------------------|
decimal | F | decimal
integer | N | numeric **
double | N | numeric **
json | J | json
variant | U | variant ***

** Por mais que o identificador dos tipos sejam diferentes, será assumido pelo ProtheusDoc em ambos casos como `numeric`. Comportamento baseado na documentação dos tipos nativos do TL++: https://tdn.totvs.com/display/tec/Tipos+Nativos

*** Caso não seja detectado/informado um tipo, será assumido o tipo `variant` pelo ProtheusDoc, mesmo que o fonte seja AdvPL e não TL++.
