### ISSUE TITLE
Tipos primitivos do TL++ no retorno e parâmetros

### ISSUE THREAD

**Issue by guilhermebigois** [AlencarGabriel/ProtheusDoc-VsCode#66]
Atualmente na linguagem TL++ temos mais tipos de dados (primitivos) que na linguagem ADVPL (vide [Tipos Nativos - TL++](https://tdn.totvs.com/display/tec/Tipos+Nativos)), contudo ao incluir o **tipo Variant** por exemplo (ex: `xRet`), o mesmo é criticado pela extensão:
![image](https://user-images.githubusercontent.com/22408258/119899720-e01cbf00-bf19-11eb-8459-5bda83eab6fc.png)

Lembrando que na linguagem ADVPL, **por mais que não tenhamos o tipo Variant, é muito comum ser criada uma variável que retorne tipos primitivos diferentes a dependendo do evento** (principalmente em [pontos de entrada MVC](https://tdn.totvs.com/pages/releaseview.action?pageId=208345968)).

**Comment by guilhermebigois** [comment]
Caso seja possível, se me disser qual arquivo efetua a validação desses tipos, posso fazer a alteração e enviar um PR.

**Comment by AlencarGabriel** [comment]
Olá @guilhermebigois,

estamos terminando de fechar alguns assuntos referente as novas mudanças do TL++ aqui na TOTVS, e vamos atualizar as extensões o quanto antes com as novidades. Já está aqui no radar.

De qualquer forma, se esses warnings estiverem incomodando, pode estar utilizando a configuração protheusDoc.marcadores_nao_validar para suprimi-los por hora, enquanto a correção não sai.

Agradeço o feedback.

**Comment by AlencarGabriel** [comment]
Duplicado com a #64.
