### ISSUE TITLE
Quando o nome da função contém o caracter "_" (underline), a documentação gerada suprime o restante.

### ISSUE THREAD

**Issue by leandromichelsen** [AlencarGabriel/ProtheusDoc-VsCode#76]
Exemplo:

/*/{Protheus.doc} FS_Proc
Rotina de processamento da importação de ativo imobilizado via TXT
@type ...
/*/

Está sendo gerado na documentação:
FS function
Rotina de processamento da importação de ativo imobilizado via TXT

**Comment by AlencarGabriel** [comment]
Olá @leandromichelsen , consegui reproduzir o problema. Realmente a documentação exportada HTML está suprimindo o nome das funções com `_`.

Estou com uma alta demanda no momento, por isso estou meio parado nas correções e melhorias da extensão. Se sentir o desejo e quiser colaborar para correção desse bug, poderia estar fazendo diretamente nesse projeto: https://github.com/robsonrosilva/protheusDoc e com certeza receberá os agradecimentos e considerações necessárias, seria de muita ajuda!

**Comment by AlencarGabriel** [comment]
Corrigido na versão **0.10.0**.
