### ISSUE TITLE
Grava sempre o mesmo nome index

### ISSUE THREAD

**Issue by EuroAmerican** [AlencarGabriel/ProtheusDoc-VsCode#78]
Quando salva o documento ele cria um index e file porem se salvar outro programa e grava em cima do que existe, como posso determinar que quando salve o nome seja mudado e tenho uma lista de paginas salvas de cada programa

**Comment by AlencarGabriel** [comment]
Olá @EuroAmerican , ao gerar a documentação HTML dos ProtheusDoc, ele não cria uma página por arquivo. Esse comportamento era como funcionava no antigo TDS Eclipse. 

A implementação que esta extensão tem é dinâmica, sendo assim ele cria um arquivo `data.js`, e neste contém toda estrutura gerada para alimentar o **index**.

Por isso lhe recomendado gerar essa documentação para um [repositório/workspace](https://github.com/AlencarGabriel/ProtheusDoc-VsCode/wiki/Documenta%C3%A7%C3%A3o-HTML#documenta%C3%A7%C3%A3o-da-workspace) inteiro, não a por arquivo.
