### ISSUE TITLE
Gerar Documentação HTML - Pastas

### ISSUE THREAD

**Issue by edhornberger** [AlencarGabriel/ProtheusDoc-VsCode#79]
Quando um Projeto contém SubPastas não estão sendo gerados os HTMLs cos fontes que estão nos menores níveis de pastas
[Uploading GerarHTMLPAsta.zip…]()

**Comment by AlencarGabriel** [comment]
Olá @edhornberger , como você fez essa geração?

Pois fazendo vi menu de contexto na pasta raiz ele pegou todos as subpastas (conforme imagem abaixo), esse projeto já começou considerando que a documentação segue a estrutura de pastas do projeto.

![image](https://github.com/AlencarGabriel/ProtheusDoc-VsCode/assets/10109480/09755cb9-a96f-4fd9-9f9c-3bb45bb7d745)

Menu de contexto:
![image](https://github.com/AlencarGabriel/ProtheusDoc-VsCode/assets/10109480/5fde324b-63d8-4147-8670-37c27a7719b2)

**Comment by edhornberger** [comment]
Olá Gabriel. 

 

Fiz desta forma que vc está indicando nas imagens. Cliquei na pasta Principal (Neste exemplo que te mandei +PET) do Projeto e selecionei a Opção “ProtheusDoc – Gerar documentação HTML - Pasta”. 

Para os fontes que estavam nesta pasta foi gerado o HTML corretamente com as informações do ProtheusDOC. Mas para os fontes que estão nas subpastas gera o HTML sem as informações (conforme o vídeo enviado). 

 

 

  _____  

		

  <https://static.wixstatic.com/media/f8df36_7a100f35e1bb4f4f90af7ce3c6812e2d~mv2.png/v1/fill/w_176,h_141,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/f8df36_7a100f35e1bb4f4f90af7ce3c6812e2d~mv2.png> 

Edson Hornberger

Consultoria em Processos e Sistemas

Contato: <https://wa.me/551199380-6772> (11) 99380-6772

E-mail:  ***@***.***> ***@***.***

 	

 <http://linkedin.com/in/edson-hornberger-214539b5> 

 <https://wa.me/5511993806772> 

 <tel:5511993806772> 

				 	
  _____  


De: Gabriel Alencar ***@***.***> 
Enviada em: terça-feira, 7 de novembro de 2023 15:09
Para: AlencarGabriel/ProtheusDoc-VsCode ***@***.***>
Cc: Edson Hornberger ***@***.***>; Mention ***@***.***>
Assunto: Re: [AlencarGabriel/ProtheusDoc-VsCode] Gerar Documentação HTML - Pastas (Issue #79)

 

Olá @edhornberger <https://github.com/edhornberger>  , como você fez essa geração?

Pois fazendo vi menu de contexto na pasta raiz ele pegou todos as subpastas (conforme imagem abaixo), esse projeto já começou considerando que a documentação segue a estrutura de pastas do projeto.

 <https://user-images.githubusercontent.com/10109480/281138506-09755cb9-a96f-4fd9-9f9c-3bb45bb7d745.png> 

Menu de contexto:
 <https://user-images.githubusercontent.com/10109480/281138959-5fde324b-63d8-4147-8670-37c27a7719b2.png>

**Comment by AlencarGabriel** [comment]
@edhornberger se puder enviar o vídeo direto pelo github, não chegou nenhum vídeo.

**Comment by edhornberger** [comment]
Já está lá...

 

  _____  

		

  <https://static.wixstatic.com/media/f8df36_7a100f35e1bb4f4f90af7ce3c6812e2d~mv2.png/v1/fill/w_176,h_141,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/f8df36_7a100f35e1bb4f4f90af7ce3c6812e2d~mv2.png> 

Edson Hornberger

Consultoria em Processos e Sistemas

Contato: <https://wa.me/551199380-6772> (11) 99380-6772

E-mail:  ***@***.***> ***@***.***

 	

 <http://linkedin.com/in/edson-hornberger-214539b5> 

 <https://wa.me/5511993806772> 

 <tel:5511993806772> 

				 	
  _____  


De: Gabriel Alencar ***@***.***> 
Enviada em: quarta-feira, 8 de novembro de 2023 10:01
Para: AlencarGabriel/ProtheusDoc-VsCode ***@***.***>
Cc: Edson Hornberger ***@***.***>; Mention ***@***.***>
Assunto: Re: [AlencarGabriel/ProtheusDoc-VsCode] Gerar Documentação HTML - Pastas (Issue #79)

 

@edhornberger <https://github.com/edhornberger>  se puder enviar o vídeo direto pelo github, não chegou nenhum vídeo.

**Comment by AlencarGabriel** [comment]
Não está, e o link está inválido.

![image](https://github.com/AlencarGabriel/ProtheusDoc-VsCode/assets/10109480/36182bdb-6ece-49ca-8f19-b477a8d7e808)

**Comment by edhornberger** [comment]
Segue o arquivo compactado com o vídeo

 

 

  _____  

		

  <https://static.wixstatic.com/media/f8df36_7a100f35e1bb4f4f90af7ce3c6812e2d~mv2.png/v1/fill/w_176,h_141,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/f8df36_7a100f35e1bb4f4f90af7ce3c6812e2d~mv2.png> 

Edson Hornberger

Consultoria em Processos e Sistemas

Contato: <https://wa.me/551199380-6772> (11) 99380-6772

E-mail:  ***@***.***> ***@***.***

 	

 <http://linkedin.com/in/edson-hornberger-214539b5> 

 <https://wa.me/5511993806772> 

 <tel:5511993806772> 

				 	
  _____  


De: Gabriel Alencar ***@***.***> 
Enviada em: quarta-feira, 8 de novembro de 2023 10:01
Para: AlencarGabriel/ProtheusDoc-VsCode ***@***.***>
Cc: Edson Hornberger ***@***.***>; Mention ***@***.***>
Assunto: Re: [AlencarGabriel/ProtheusDoc-VsCode] Gerar Documentação HTML - Pastas (Issue #79)

 

@edhornberger <https://github.com/edhornberger>  se puder enviar o vídeo direto pelo github, não chegou nenhum vídeo.

**Comment by AlencarGabriel** [comment]
via e-mail não costuma vir os anexos

![image](https://github.com/AlencarGabriel/ProtheusDoc-VsCode/assets/10109480/a286ec89-657a-4eaa-8542-e55b25031e52)

**Comment by edhornberger** [comment]
[ProtheusDOC.zip](https://github.com/AlencarGabriel/ProtheusDoc-VsCode/files/13297110/ProtheusDOC.zip)

**Comment by edhornberger** [comment]
Subi o arquivo pelo Git

 

  _____  

		

  <https://static.wixstatic.com/media/f8df36_7a100f35e1bb4f4f90af7ce3c6812e2d~mv2.png/v1/fill/w_176,h_141,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/f8df36_7a100f35e1bb4f4f90af7ce3c6812e2d~mv2.png> 

Edson Hornberger

Consultoria em Processos e Sistemas

Contato: <https://wa.me/551199380-6772> (11) 99380-6772

E-mail:  ***@***.***> ***@***.***

 	

 <http://linkedin.com/in/edson-hornberger-214539b5> 

 <https://wa.me/5511993806772> 

 <tel:5511993806772> 

				 	
  _____  


De: Gabriel Alencar ***@***.***> 
Enviada em: quarta-feira, 8 de novembro de 2023 10:22
Para: AlencarGabriel/ProtheusDoc-VsCode ***@***.***>
Cc: Edson Hornberger ***@***.***>; Mention ***@***.***>
Assunto: Re: [AlencarGabriel/ProtheusDoc-VsCode] Gerar Documentação HTML - Pastas (Issue #79)

 

via e-mail não costuma vir os anexos

 <https://user-images.githubusercontent.com/10109480/281415519-a286ec89-657a-4eaa-8542-e55b25031e52.png>

**Comment by AlencarGabriel** [comment]
Analisando o vídeo entendi o caso, vou fazer uns testes. Acredito ser algum problema por conta dos caracteres especiais no nome da pasta. A lib é multi SO, e no linux por exemplo esses caracteres no nome da pasta costuma dar uns problemas.

**Comment by AlencarGabriel** [comment]
Corrigido na versão **0.10.0**.
