### ISSUE TITLE
Problema Encoding ANSI HTML ao Disponibilizar ProtheusDoc HTML em Servidor WEB PRotheus

### ISSUE THREAD

**Issue by carloseniemeyer** [AlencarGabriel/ProtheusDoc-VsCode#86]
Problema Encoding ANSI HTML ao Disponibilizar ProtheusDoc HTML em Servidor WEB Protheus

Ao gerar o ProtheusDoc HTML é gerado o arquivo HTML com o **Charset UTF-8:**
`<meta charset="utf-8" />`

E todos os arquivos (html, css, js) com o encoding UTF-8.

No Conteúdo gerado existem palavras acentuadas (**Código Fonte no Padrão ANSI - Windows 1252**).

Ao exibir o arquivo HTML direto no navegador Chrome/Edge é apresentado o conteúdo HTML com a acentuação correta nas palavras.

Ao disponibilizar o conteúdo HTML para ser exibido em um Servidor WEB HTTP (No caso pelo Próprio Protheus) para acesso por time de Devs e Funcionais, o conteúdo acentuado é apresentado de forma incorreta com os caracteres misturados.

**Imagem Acessando Direto no Navegador - Arquivo Local**
![image](https://github.com/AlencarGabriel/ProtheusDoc-VsCode/assets/52763295/941796e3-6e55-40fa-9af4-f2ca89a4b0db)

**Imagem Acessando via HTTP Server:**
_(Mesmos Arquivos)_
![image](https://github.com/AlencarGabriel/ProtheusDoc-VsCode/assets/52763295/6204f9d1-e429-4563-8a87-83bdb12d2c98)

Seria possível gerar o Arquivos HTMLs gerados no mesmo encoding dos códigos fontes (Windows 1252) e o HTML com o Charset equivalente?
`<meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">`

**Poderia existir uma parametrização para isso no VsCode - Plugin do ProtheusDoc?**

A acentuação fica certa somente ao converter todos os arquivos gerados para ANSI pelo Notepad++ e ao colocar o charset correto nos arquivos HTMLs.

**Comment by AlencarGabriel** [comment]
Olá @carloseniemeyer .

Dei uma olhada no projeto que gera a parte HTML, e constatei que todo o projeto é por padrão codificado com UTF-8, não identifiquei discrepâncias. Até mesmo o data.js (conteúdo das documentações) está codificado assim. Não é atoa que ao visualizar no navegador localmente não temos problemas de encoding.

Creio que o problema que está tendo seja no nível do server do Protheus, pois ele sim trabalha como padrão com Win 1252, e pode ser que ele está abrindo os arquivos com essa codificação padrão, o que necessitaria de uma conversão ou tratamento no server para trabalhar como Win 1252. 

O padrão da web é UTF-8, não vejo sentido geral em alterar o projeto para isso, creio que dê para você solucionar na camada do server, inclusive sem precisar converter no notepad++ (como vc tem feito).

Sobre a questão de parametrizar, até tenha uma certa validade se você não conseguir resolver na camada do server. Mas não estou em condições no momento para realizar o ajuste. Agradeceríamos um pull request contribuindo com essa feature. 

O projeto da documentação HTML é este: https://github.com/robsonrosilva/protheusDoc

**Comment by carloseniemeyer** [comment]
Obrigado pelo retorno @AlencarGabriel !
Vou investigar com o Time aqui as possibilidades.
Eu ainda não encontrei referências de configurações do Arquivo ini do AppServer e nem parâmetros SX6 que poderiam ser utilizados para alterar de ANSI para UTF-8, mas continuarei buscando.
Sobre o PR no Projeto aqui vou ver com o time quem teria conhecimentos para fazer essa melhoria.
